### ISSUE TITLE
Move all bot logic in the main class into plugins

### ISSUE THREAD

**Issue by bluskript** [Geoxor/Naoko#102]
Example: nickname emojification should be a plugin
https://github.com/Geoxor/Shaii/blob/main/src/shaii/Shaii.shaii.ts#L306
Mute behavior should also be a plugin too
https://github.com/Geoxor/Shaii/blob/main/src/shaii/Shaii.shaii.ts#L435

**Comment by Geoxor** [comment]
these require massive refactors from how spaghetti it is 💀💀💀💀

**Comment by qexat** [comment]
if it works it works :trollface:
