### ISSUE TITLE
Can't launch the Shaii

### ISSUE THREAD

**Issue by riichimaru** [Geoxor/Naoko#137]
Hi, I'm using Ubuntu-based distro and when I'm trying to launch Shaii I have this error.

Here's the console output:

__Error: Cannot find module 'chalk'
Require stack:
- /home/tokidesu/Shaii/src/shaii.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/tokidesu/.nvm/versions/node/v16.6.0/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/tokidesu/Shaii/src/shaii.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/tokidesu/.nvm/versions/node/v16.6.0/lib/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tokidesu/.nvm/versions/node/v16.6.0/lib/node_modules/ts-node/src/index.ts:1458:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/tokidesu/Shaii/src/shaii.ts' ]
}
[nodemon] app crashed - waiting for file changes before starting..._

I have done all from readme, and even if the error is in chalk, when I'm trying to install it, I'm getting another error.

Here's the output for this.

tokidesu@Lenovo-G70-35:~/Shaii$ npm install chalk
npm WARN deprecated @types/file-type@10.9.1: This is a stub types definition. file-type provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/tokidesu/Shaii/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! (node:23679) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/.cache/node-gyp/16.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/tokidesu/.cache/node-gyp/16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/tokidesu/Shaii/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/tokidesu/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/tokidesu/Shaii/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: Permission denied
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/tokidesu/Shaii/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.17.0-3.2-liquorix-amd64
npm ERR! gyp ERR! command "/home/tokidesu/Shaii/node_modules/node/bin/node" "/home/tokidesu/Shaii/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/tokidesu/Shaii/node_modules/gl
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tokidesu/.npm/_logs/2022-04-24T15_18_18_198Z-debug.log

I'm sorry if this is easy-solved problem, but I'm a newbie in Linux systems.

**Comment by otiskujawa** [comment]
What commands did you enter?
You should run:

> nvm install 16.6.0 && nvm use 16.6.0 
> CXX=gcc-10 npm ci

to install modules

**Comment by tokidesu-zero** [comment]
> What commands did you enter? You should run:
> 
> > nvm install 16.6.0 && nvm use 16.6.0
> > CXX=gcc-10 npm ci
> 
> to install modules

At first I ran these commands, and all was good, but now I'm getting this output:

npm WARN deprecated @types/file-type@10.9.1: This is a stub types definition. file-type provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/tokidesu/Shaii/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! (node:24558) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/.cache/node-gyp/16.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/tokidesu/.cache/node-gyp/16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/tokidesu/Shaii/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/tokidesu/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/tokidesu/Shaii/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: Permission denied
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/tokidesu/Shaii/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.17.0-3.2-liquorix-amd64
npm ERR! gyp ERR! command "/home/tokidesu/Shaii/node_modules/node/bin/node" "/home/tokidesu/Shaii/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/tokidesu/Shaii/node_modules/gl
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tokidesu/.npm/_logs/2022-04-24T15_44_53_155Z-debug.log

**Comment by otiskujawa** [comment]
Similar to
#122

**Comment by tokidesu-zero** [comment]
> Similar to #122

Sorry, I don't get it. I need to change system files, but which of them?

**Comment by Geoxor** [comment]
thats weird, make sure you are installing chalk 4.0.0 because chalk 5 doesn't work without ESM, 
i also noticed this 
![image](https://user-images.githubusercontent.com/34042825/165083972-43d7b0ad-1ef9-43ca-9e9f-bf6604e2b995.png)

check if your python bin has execute permissions for your user?

**Comment by Geoxor** [comment]
this should be all you need to run the bot, at least this works on debian and on the ubuntu github runners

```bash
sudo apt install -y build-essential g++-10 libxi-dev libxext-dev libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev libjpeg-dev librsvg2-dev mesa-common-dev

npm i 

npm run dev
```

**Comment by tokidesu-zero** [comment]
> thats weird, make sure you are installing chalk 4.0.0 because chalk 5 doesn't work without ESM, i also noticed this ![image](https://user-images.githubusercontent.com/34042825/165083972-43d7b0ad-1ef9-43ca-9e9f-bf6604e2b995.png)
> 
> check if your python bin has execute permissions for your user?

So, when I tried to install chalk, I got this:

npm WARN deprecated @types/file-type@10.9.1: This is a stub types definition. file-type provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/tokidesu/Shaii/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! (node:6151) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/Shaii/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tokidesu/.cache/node-gyp/16.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/tokidesu/.cache/node-gyp/16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/tokidesu/Shaii/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/tokidesu/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/tokidesu/Shaii/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: Permission denied
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/tokidesu/Shaii/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.17.0-3.2-liquorix-amd64
npm ERR! gyp ERR! command "/home/tokidesu/Shaii/node_modules/node/bin/node" "/home/tokidesu/Shaii/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/tokidesu/Shaii/node_modules/gl
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tokidesu/.npm/_logs/2022-04-25T12_47_25_263Z-debug.log

About python, sorry, I dunno how to check perms, so can you please tell me how? I searched for it like an hour and got nothing.

**Comment by Geoxor** [comment]
the thing is when you do `npm i chalk@4.0.0` npm also tries to install the rest of the dependancies resulting into it trying to recompile OpenGL judging by this line 
![image](https://user-images.githubusercontent.com/34042825/165113260-7f87480b-c50c-4f54-ac28-dbf73b4daf11.png)

then python errors out with exist status 127 because of lacking permissions

try deleting the `node_modules` folder and try installing everything with `sudo npm i`

if that doesn't work then im not quite sure what the problem is..
